# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:

        in_memory:
            memory:
               users:
                  user: { password: userpass , roles: ['ROLE_USER'] }

        our_users:
            entity: { class: UserBundle:Person , property: email  }




    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            stateless: false

            form_login:
                login_path: /login
                check_path: login_check

            logout:
                path: logout

#            guard:
#                authenticators:
#                    - app.security.login_form_authenticator



    access_control:
        - { path: ^/user, roles: ROLE_USER } #, requires_channel: https


    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
